"""baseline

Revision ID: baec48901c74
Revises:
Create Date: 2026-03-09 07:31:19.536339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op  # type: ignore[import-not-found]

# revision identifiers, used by Alembic.
revision: str = "baec48901c74"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parsed_criteria", sa.Text(), nullable=True),
        sa.Column("auto_refresh", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preference_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_type", "key", name="uq_rule_type_key"),
    )
    op.create_table(
        "set_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("target_bpm_start", sa.Float(), nullable=True),
        sa.Column("target_bpm_end", sa.Float(), nullable=True),
        sa.Column("energy_arc", sa.String(length=100), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_crate_ids", sa.Text(), nullable=True),
        sa.Column("harmonic_mixing", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("source_format", sa.Text(), nullable=True),
        sa.Column("source_codec", sa.Text(), nullable=True),
        sa.Column("source_bitrate", sa.Integer(), nullable=True),
        sa.Column("source_bit_depth", sa.Integer(), nullable=True),
        sa.Column("output_format", sa.Text(), nullable=True),
        sa.Column("codec", sa.Text(), nullable=True),
        sa.Column("bit_rate", sa.Integer(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("bit_depth", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("is_lossy", sa.Boolean(), nullable=True),
        sa.Column("quality_warning", sa.Boolean(), nullable=False),
        sa.Column("conversion_action", sa.Text(), nullable=True),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("artist", sa.Text(), nullable=True),
        sa.Column("album", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("composer", sa.Text(), nullable=True),
        sa.Column("remixer", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("mix_name", sa.Text(), nullable=True),
        sa.Column("grouping", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("key", sa.Integer(), nullable=True),
        sa.Column("key_text", sa.Text(), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("colour", sa.Text(), nullable=True),
        sa.Column("source_bpm", sa.Float(), nullable=True),
        sa.Column("source_key", sa.Integer(), nullable=True),
        sa.Column("bpm_confidence", sa.Float(), nullable=True),
        sa.Column("key_confidence", sa.Float(), nullable=True),
        sa.Column("analysis_status", sa.Text(), nullable=False),
        sa.Column("subgenre", sa.Text(), nullable=True),
        sa.Column("mood", sa.Text(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("ai_confidence", sa.String(length=10), nullable=True),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("source_genre", sa.Text(), nullable=True),
        sa.Column("ai_status", sa.Text(), nullable=False),
        sa.Column("import_source", sa.String(length=50), nullable=True),
        sa.Column("import_conflicts", sa.Text(), nullable=True),
        sa.Column("proposed_path", sa.Text(), nullable=True),
        sa.Column("previous_output_path", sa.Text(), nullable=True),
        sa.Column("organisation_status", sa.Text(), nullable=False),
        sa.Column("organisation_confidence", sa.Float(), nullable=True),
        sa.Column("organisation_reasoning", sa.Text(), nullable=True),
        sa.Column("date_added", sa.Text(), nullable=False),
        sa.Column("date_modified", sa.Text(), nullable=False),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("last_played", sa.Text(), nullable=True),
        sa.Column("conversion_status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index("ix_tracks_file_hash", ["file_hash"], unique=True)

    op.create_table(
        "crate_tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crate_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("assignment_method", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["crate_id"], ["crates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crate_id", "track_id", name="uq_crate_track"),
    )
    op.create_table(
        "set_segments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_track_position", sa.Integer(), nullable=False),
        sa.Column("end_track_position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["set_id"], ["set_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "set_tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("is_candidate", sa.Boolean(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["segment_id"], ["set_segments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["set_id"], ["set_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("set_id", "track_id", name="uq_set_track"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("set_tracks")
    op.drop_table("set_segments")
    op.drop_table("crate_tracks")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index("ix_tracks_file_hash")

    op.drop_table("tracks")
    op.drop_table("set_plans")
    op.drop_table("preference_rules")
    op.drop_table("crates")
    # ### end Alembic commands ###
